[package]

name = "nickel_postgres"
version = "0.0.0"
authors = [
    "bguiz"
]

[dependencies]
postgres = "*"
r2d2 = "*"
r2d2_postgres = "*"
plugin = "*"
typemap = "*"
openssl = "*"

[dependencies.nickel]
git = "https://github.com/Ryman/nickel.rs"
branch = "dev"
